<?php
/* Template Name: Single Ujian */

wp_head();
?>
<!DOCTYPE html>
<html <?php language_attributes(); ?>>

<head>
    <meta charset="<?php bloginfo('charset'); ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.14.0/js/all.js"></script>
    <style>
        body,
        html {
            height: 100%;
            margin: 0;
        }

        .full-height {
            height: 100%;
        }

        .navbar {
            background-color: #222;
        }

        .sidebar {
            position: fixed;
            top: 0;
            bottom: 0;
            left: 0;
            background-color: #222;
            width: 250px;
            display: none;
            overflow-y: auto;
            z-index: 10;
        }

        .sidebar ul {
            list-style-type: none;
            padding: 0;
        }

        .sidebar ul li a {
            display: block;
            color: #fff;
            padding: 8px 16px;
            text-decoration: none;
        }

        .sidebar ul li a:hover {
            background-color: #444;
        }

        .toggle-sidebar {
            cursor: pointer;
        }

        .timer {
            font-size: 1.25rem;
        }

        .sidebar ul.section-title {
            font-weight: bold;
            margin-top: 1rem;
            padding: 0.5rem 1rem;
            background-color: #444;
        }
    </style>
</head>

<body <?php body_class('full-height'); ?>>

    <nav class="navbar is-dark">
        <div class="navbar-brand">
            <span class="navbar-item toggle-sidebar">
                <i class="fas fa-bars"></i>
            </span>
            <div class="navbar-item timer">
                00:00
            </div>
        </div>

        <div class="navbar-end">
            <div class="navbar-item">
                <?php echo get_the_author_meta('display_name'); ?>
            </div>
        </div>
    </nav>

    <div class="sidebar">
        <ul class="question-navigation">
            <!-- Navigation items will be generated by JavaScript -->
        </ul>
    </div>

    <main class="container full-height" id="question-container">
        <!-- Questions will be loaded here -->
    </main>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        $(document).ready(function() {
            const questions = [{
                    id: 1,
                    type: 'pg',
                    label: 'Pilihan Ganda'
                },
                {
                    id: 2,
                    type: 'pg',
                    label: 'Pilihan Ganda'
                },
                {
                    id: 3,
                    type: 'pg',
                    label: 'Pilihan Ganda'
                },
                {
                    id: 4,
                    type: 'pg',
                    label: 'Pilihan Ganda'
                },
                {
                    id: 5,
                    type: 'pg',
                    label: 'Pilihan Ganda'
                },
                {
                    id: 6,
                    type: 'bs',
                    label: 'Benar Salah'
                },
                {
                    id: 7,
                    type: 'bs',
                    label: 'Benar Salah'
                },
                {
                    id: 8,
                    type: 'bs',
                    label: 'Benar Salah'
                },
                {
                    id: 9,
                    type: 'bs',
                    label: 'Benar Salah'
                },
                {
                    id: 10,
                    type: 'bs',
                    label: 'Benar Salah'
                },
                {
                    id: 11,
                    type: 'esai',
                    label: 'Esai'
                },
                {
                    id: 12,
                    type: 'esai',
                    label: 'Esai'
                },
                {
                    id: 13,
                    type: 'esai',
                    label: 'Esai'
                },
                {
                    id: 14,
                    type: 'dok',
                    label: 'Dokumen'
                }
            ];

            let currentQuestion = 0;

            function loadQuestion(index) {
                const question = questions[index];
                let questionHTML = '';

                switch (question.type) {
                    case 'pg':
                        questionHTML = `
                            <div class="box">
                                <h3 class="title">${question.label} ${question.id}</h3>
                                <div class="content">
                                    <!-- Add your multiple choice question content here -->
                                </div>
                            </div>`;
                        break;
                    case 'bs':
                        questionHTML = `
                            <div class="box">
                                <h3 class="title">${question.label} ${question.id}</h3>
                                <div class="content">
                                    <!-- Add your true/false question content here -->
                                </div>
                            </div>`;
                        break;
                    case 'esai':
                        questionHTML = `
                            <div class="box">
                                <h3 class="title">${question.label} ${question.id}</h3>
                                <div class="content">
                                    <!-- Add your essay question content here -->
                                </div>
                            </div>`;
                        break;
                    case 'dok':
                        questionHTML = `
                            <div class="box">
                                <h3 class="title">${question.label} ${question.id}</h3>
                                <div class="content">
                                    <!-- Add your document upload question content here -->
                                </div>
                            </div>`;
                        break;
                }

                $('#question-container').html(questionHTML);
                currentQuestion = index;
            }

            function generateNavigation() {
                let navHTML = '';
                const questionTypes = ['pg', 'bs', 'esai', 'dok'];
                const typeLabels = {
                    'pg': 'Pilihan Ganda',
                    'bs': 'Benar Salah',
                    'esai': 'Esai',
                    'dok': 'Dokumen'
                };

                questionTypes.forEach(type => {
                    navHTML += `<li class="section-title">${typeLabels[type]}</li>`;
                    questions.filter(q => q.type === type).forEach((question, index) => {
                        navHTML += `<li><a href="#" data-index="${index}">${question.label} ${question.id}</a></li>`;
                    });
                });

                $('.question-navigation').html(navHTML);
            }


            $('.toggle-sidebar').on('click', function() {
                $('.sidebar').toggle();
            });

            $('.question-navigation').on('click', 'a', function(e) {
                e.preventDefault();
                const index = $(this).data('index');
                loadQuestion(index);
                $('.sidebar').hide();
            });

            // Initialize the navigation and load the first question
            generateNavigation();
            loadQuestion(currentQuestion);

            // Timer
            let timer = 0;
            setInterval(function() {
                timer++;
                let minutes = Math.floor(timer / 60);
                let seconds = timer % 60;

                $('.timer').text(`${minutes.toString().padStart(2, '0')}:${seconds.toString().padStart(2, '0')}`);
            }, 1000);
        });
    </script>

    <?php
    wp_footer();
    ?>
</body>

</html>